# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: remitano
  pool: 5
  username: postgres
  password: admin@123
  host: localhost
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: remitano
  pool: 5
  username: root
  password: admin@123
  host: localhost

beta:
  adapter: mysql2
  database: 
  username: 
  password: 
  socket: 
  host: 
  secure_auth: false


production:
  adapter: mysql2
  database: 
  username: 
  password: 
  socket: /var/run/mysqld/mysqld.sock
  host: 
  secure_auth: false
